name: 'docker-compose smart health checker'
description: 'This action reads docker-compose.yml and identify exposed ports to try to health check. Try to guess protocol based on image name.'
inputs:
  blacklist-ports:
    description: 'Ports to blacklist and not run health checks'
    required: false
    default: '[]'
  check-timeout:
    description: 'Timeout for health checks'
    required: false
    default: 30

runs:
  using: "composite"
  steps:
    - name: Download latest slashping
      uses: robinraju/release-downloader@v1.3
      with:
        repository: "caquino/slashping"
        latest: true
        fileName: "slashping_*_Linux_x86_64.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract slashping release
      shell: bash
      run: |
        tar -zxvpf slashping_*_Linux_x86_64.tar.gz
    - name: Execute slashping
      shell: bash
      run: |
        ./slashping